import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import { SignIn, UserButton, useUser } from "@clerk/nextjs";
import { SignInButton } from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="text-lg font-semibold text-white">
          {!user.isSignedIn && <SignInButton />}
        </div>
        <div className="text-lg font-semibold text-white">
          {!!user.isSignedIn && <UserButton />}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        <div>
          {data?.map((post) => (
            <div
              className="my-5 text-lg font-semibold text-white"
              key={post.id}
            >
              {post.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
